### ISSUE TITLE
could the method load_test_data in instance_helpers receive more parameters??

### ISSUE THREAD

**Issue by lfalvarez** [mysociety/popit-django#18]
like for example project_root and/or the exact path from where to get the fixture to load?
I created a method (very untidy one) that loads the data into the testing popit api. What I did was, copied the one in [instance_helpers.py](https://github.com/mysociety/popit-django/blob/master/popit/tests/instance_helpers.py#L24) and modified [line 35](https://github.com/mysociety/popit-django/blob/master/popit/tests/instance_helpers.py#L35) and [line 40](https://github.com/mysociety/popit-django/blob/master/popit/tests/instance_helpers.py#L40) and this was [the result](https://github.com/ciudadanointeligente/write-it/blob/create_instance_with_popit_api/global_test_case.py#L22-L27).

**Comment by tmtmtmtm** [comment]
Closing, as this project is deprecated in favour of https://github.com/openpolis/django-popolo
