### ISSUE TITLE
create "example_project" to allow easier testing and development

### ISSUE THREAD

**Issue by osfameron** [mysociety/popit-django#20]
currently there's no top level "site" project -- though this makes sense (as the project is never intended to be used by itself, but always within other django sites) this means that:

 a) some clever workarounds are needed to get automated testing to work at all
 b) manual testing of, e.g. data migrations, is tricky

would be much easier if this had a standard django site structure.  Calling it "example_project" or similar should maintain the point that this is not intended to be used standalone.

**Comment by tmtmtmtm** [comment]
Closing, as this project is deprecated in favour of https://github.com/openpolis/django-popolo
