### ISSUE TITLE
Null summary in popit-api makes save method of Person model to break

### ISSUE THREAD

**Issue by lfalvarez** [mysociety/popit-django#24]
When a person has summary:null in popit-api it makes fetch_all_from_api to break at the save() method. I think it could be fixed by making this method https://github.com/mysociety/popit-django/blob/master/popit/models.py#L131-L135 handle null values at summary, name or image.

**Comment by tmtmtmtm** [comment]
@lfalvarez This project has been deprecated for a while, in favour of django-popolo. We'd probably still look at merging simple bug-fix Pull Requests if this one is still an issue for you? Or have you worked around this sufficiently that it's not really worth it?

**Comment by lfalvarez** [comment]
Hey @tmtmtmtm I think it doesn't make much sense to keep this PR open.  And also I've been using our own fork of this project.

**Comment by tmtmtmtm** [comment]
Thanks @lfalvarez
