### ISSUE TITLE
deprecate this project

### ISSUE THREAD

**Issue by mhl** [mysociety/popit-django#28]
The [django-popolo](https://github.com/openpolis/django-popolo) project has a complete modelling of the Popolo spec - rather than #27 and friends, we should just write a PopIt -> popolo-django one-way sync admin command for popolo-django, make a pull request for that and then deprecate this project in favour of popolo-django.

**Comment by chrismytton** [comment]
The README for this repo already states that development on PopIt has been halted. I've also added a line to the repo description making it clear that this repo is deprecated in favour of django-popolo:

![screen shot 2016-03-09 at 15 35 16](https://cloud.githubusercontent.com/assets/22996/13640529/f94d760e-e60c-11e5-96e6-c803ecb6fdb7.png)
